### ISSUE TITLE
Google Open Source Minikube Course 

### ISSUE THREAD

**Issue by annidy** [annidy/notes#280]
## [What is minikube?](https://www.youtube.com/watch?v=uo82-n1gMcI)
Useful command
```
# show clusters
minikube profile list
# add worker node
minikube node add

# empty pods
minikube delete -all
# delete all include k8s
minikube delete -all -purge
```

## [Local development using minikube](https://www.youtube.com/watch?v=_1uWY1GdDVY&t=324s)
https://github.com/google/learn-oss-with-google/tree/main/minikube

1. enter minikube's Docker
```
# on Mac or Linux
eval $(minikube docker-env)
```
2. Build and deploy
```
docker build -t local/devex:v1 .
kubectl apply -f deploy/k8s.yaml
```
3. Aceess the deployed service
```
minikube service list
minikube service YOUR-SERVICE
```
4. Redeploy after code change
```
kubectl delete -f deploy/k8s.yaml
docker rmi local/devex:v1
```
goto step 2

### mount volume
set the `mountPath` in k8s
```
      containers:
      - name: app
        image: local/devex:v1
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /data
          name: test-volume
      volumes:
        - name: test-volume
          hostPath:
            # directory location on host
            path: /data
```

mount with minikube, in a separate window
```
minikube mount ~/Desktop/local-devex:/data/
```
